---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shpiel.fullname" . }}
  labels:
    {{- include "shpiel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "shpiel.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.ports.api }}
      targetPort: api
    - name: metrics
      port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
    {{- if .Values.config.listen.admin }}
    - name: admin
      port: {{ .Values.service.ports.admin }}
      targetPort: admin
    {{- end }}
