---
name: goreleaser

"on":
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release-binaries:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Activate Hermit
        uses: cashapp/activate-hermit@cea9af7913204a965fd488637a8d1811bba2e616 # v1
        with:
          cache: "true"

      - name: Build and attach release binaries
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
